# You can read more about all the configuration params in
# https://docs.witnet.io/configuration/toml-file/
[connections]
server_addr = "0.0.0.0:21337"
known_peers = ["192.168.1.45:21337"]
outbound_limit = 1
bootstrap_peers_period_seconds = 1

[storage]
db_path = ".witnet-local-node"

[consensus_constants]
checkpoints_period = 30
checkpoint_zero_timestamp = 1577145600
genesis_hash = "00000000000000000000000000000000000000007769746e65742d302e362e30"

[log]
level = "debug"

[wallet]
db_path = ".witnet-local-wallet"
testnet = true
node_url = "127.0.0.1:21338"
